apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "career-chatbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  MODEL_ID: {{ .Values.config.modelId | quote }}
  ASSISTANT_NAME: {{ .Values.config.assistantName | quote }}
  ME_DIR: {{ .Values.config.meDir | quote }}
