apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "career-chatbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "career-chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "career-chatbot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "career-chatbot.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "career-chatbot.fullname" . }}
            - secretRef:
                name: {{ include "career-chatbot.fullname" . }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
