apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "career-chatbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "career-chatbot.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: MAILGUN_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.secretPath }}
        property: MAILGUN_API_KEY
    - secretKey: BEDROCK_GUARDRAIL_ID
      remoteRef:
        key: {{ .Values.externalSecret.secretPath }}
        property: BEDROCK_GUARDRAIL_ID
    - secretKey: BEDROCK_GUARDRAIL_VERSION
      remoteRef:
        key: {{ .Values.externalSecret.secretPath }}
        property: BEDROCK_GUARDRAIL_VERSION
